### ISSUE TITLE
Documentation improvement request

### ISSUE THREAD

**Issue by scaleoutsean** [microsoft/Codex-CLI#112]
`CTRL + G` is not the same as `CTRL + g` (edit: but they are both used). Can the readme and installation pages pick one?

>  You can also provide examples of your own CLI commmands and scripts, to show Codex other tools it should consider using.

How?

**Comment by dluc** [comment]
hi @scaleoutsean thank you for the feedback! 

If I understand correctly, `CTRL + g` would be clearer, right? so for example one doesn't wonder whether to press the `SHIFT` key too.

About the examples: you can customize the files under `/contexts` including more examples, replacing the existing ones, etc. Bear in mind that there's an input limit on the underlying language model, so I would keep the total file size below 2500 bytes.

**Comment by scaleoutsean** [comment]
`CTRL + g` would be clearer to me personally as well, but I'm not aware if there are any conventions or preferences on your side.

/contexts: so we just add row pairs like that, that's all. Interesting!

**Comment by dluc** [comment]
From a quick search around Ctrl C, Z, V, looks like it's common to use `Ctrl` instead of `CTRL` and a capital letter for the second key, so `Ctrl + G` in our case. Sent PR https://github.com/microsoft/Codex-CLI/issues/112 to address this.

**Comment by dluc** [comment]
PR merged 👍
