### ISSUE TITLE
No response when in a conda environment 

### ISSUE THREAD

**Issue by S-Yuan137** [microsoft/Codex-CLI#117]
Known as the title. Codex-Cli no response when activating an env.
More details: Powershell 7, conda 4.12.0. 
To be honest, this is not a severe bug since we can easily access command line help if deactivate env. However, it means we can't get any help to do something within the environment.

**Comment by dluc** [comment]
@S-Yuan137 could you provide some steps to repro, that would help use looking into it.

**Comment by S-Yuan137** [comment]
It is in the windows platform. After activating a python environment using conda, the `crtl+G` doesn't get responses. If the python environment is deactivated, it becomes normal and `ctrl+G` works.

**Comment by jnflint** [comment]
were the python libraries installed into that environment (or the base environment before the env was created)?
python -m pip install -r requirements.txt in the directory with the Codex-Cli repository

**Comment by S-Yuan137** [comment]
Oh, you are right. After reading what you said, I realized that the Codex-Cli is related to python, which of course, only stays in the environment where I installed it (in my case, it is my default env, not in conda). It worked when I installed it in the environment I wanted to use. Thanks a lot!
