### ISSUE TITLE
# Codex CLI error: Rate limit exceeded, try later

### ISSUE THREAD

**Issue by solusarcticwolf** [microsoft/Codex-CLI#126]
This after doing the setup correctly.

**Comment by solusarcticwolf** [comment]
I'm using Powershell as admin, have made sure that I entered the correct model: code-davinci-002

**Comment by solusarcticwolf** [comment]
Update - it may have been because I haven't used a paid account. 
I just upgraded my account to paid on the OpenAI platform and regenerated my API keys, redid the setup.

Issue resolved.

**Comment by sameermahajan** [comment]
Does it need a paid account? If so, where does it state so?
