### ISSUE TITLE
Unexpected exception - 'PromptFile' object has no attribute 'config'

### ISSUE THREAD

**Issue by Frumpy9** [microsoft/Codex-CLI#127]
Hello!

I am attempting to install the Codex plugin for PowerShell on a machine running Windows 11. I have been able to successfully run ps1 scripts and use the control+g functionality within PowerShell, but I am encountering an error message when attempting to use the plugin. The error message reads: `# Codex CLI error: Unexpected exception - 'PromptFile' object has no attribute 'config'`. In DEBUG mode, the following message is also displayed: `prompt: `.

I am wondering if there is a configuration file that I need to create, in addition to the one that was created for me by the .ps1 file containing my keys. Alternatively, do I need to make any changes to the codex_query.py file in order to get the plugin to work properly?

Let me know if you need any more detail to help me solve this.

Thanks

**Comment by sykuang** [comment]
Same issue here. I use the workaround as below.

```
diff --git a/src/prompt_file.py b/src/prompt_file.py
index f86aeac..9229732 100644
--- a/src/prompt_file.py
+++ b/src/prompt_file.py
@@ -22,7 +22,8 @@ class PromptFile:
         # loading in one of the saved contexts
         if file_name != self.default_context_filename:
             self.load_context(file_name, True)
-
+        else:
+            self.config=config
     def has_config(self):
         """
         Check if the prompt file has a corresponding config file
```
