### ISSUE TITLE
No openaiapirc file being created with bash_setup.sh

### ISSUE THREAD

**Issue by Jordan-Bowman-Davis** [microsoft/Codex-CLI#132]
Hello,

I am trying to install this on a bash terminal on mac using the following fork to run with gpt-3.5-turbo: [https://github.com/Lukas-LLS/Codex-CLI](https://github.com/Lukas-LLS/Codex-CLI)

The setup script does not seem to be creating the `openaiapirc` file in `/src`, leading to the following error. No errors are thrown on setup. Has anyone else experienced this? Thank you!

```***********************************************
Open a new Bash terminal, type '#' followed by
your natural language command and hit Ctrl + G!
***********************************************
(base) ~/Documents/Code Projects/CodexCli/scripts> # what's my ip?
wc: /Users/jordanbowman-davis/Documents/Code: open: No such file or directory
wc: Projects/CodexCli/src/openaiapirc: open: No such file or directory
Codex CLI configuration is missing, try reinstalling```

**Comment by Lukas-LLS** [comment]
This problem most likely appears because there is a space in the name of your `Code Projects` folder, the path handling of the setup script most probably breaks because of that.
